spring.application.name=spring_boot_java_random_user

# Swagger UI custom path
springdoc.swagger-ui.path=/api

# URL for Random User API
dummy.api.base-url=${DUMMY_API_BASE_URL}

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


# Spring Data JDBC - Initialize database
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=
spring.sql.init.platform=postgresql
spring.sql.init.continue-on-error=true
