spring.application.name=spring_boot_java_random_user

# Swagger UI custom path
springdoc.swagger-ui.path=/api

# URL for Random User API
randomuser.api.base-url=https://dummyjson.com/

# Database configuration
spring.datasource.url=jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Liquibase configuration
spring.liquibase.enabled=${SPRING_LIQUIBASE_ENABLED:true}
spring.liquibase.change-log=classpath:${LB_CHANGELOG}
spring.liquibase.default-schema=${LB_SCHEMA}
